/**
 * riskCalculatorService.js
 *
 * Every formula the Risk Calculator uses, extracted from
 * "Lotaje_por_SL_5000usd.xlsx" (sheet "Calculadora FX $5000.csv") and kept
 * completely separate from any component — no JSX, no React state, no DOM.
 * This is the "RiskCalculatorService" called for in the architecture: pure
 * functions in, values out, so the math can be verified independently of
 * how it's displayed and reused by any future widget or tool.
 *
 * ── Source formulas (Excel cell references, $5000 sheet) ──────────────────
 *   D2  Riesgo teórico  = $C$11 * $C$12              (Balance * Risk%)
 *   E2  Valor pip       = VLOOKUP(instrument, ...)   (→ instrumentConfig.js's pointValue)
 *   C2  Lotaje estimado = D2 / (B2 * E2)              (RiesgoUSD / (SL * pointValue))
 *
 * Verified against the reference screenshot (Balance $5,000, Risk 0.70% →
 * Risk $35.00): NAS100 35/61.24=0.5715→0.57 ✓, SP500 35/7.61=4.5992→4.60 ✓,
 * US30 35/102.35=0.3420→0.34 ✓ — all three match exactly.
 *
 * The Excel's "Redondeo" (broker lot-step rounding) and "Riesgo exacto"
 * (risk recomputed after that rounding) columns were initially left out of
 * this port, then added back for a global "current-state" risk display.
 * They've since grown into the calculator's real navigation model:
 * riskDollarFromPercent() is still the flat theoretical target (used for
 * the Settings screen and as the reference every lot is measured against),
 * but optimalLot() below is what actually gets shown and traded — the real
 * broker-tradeable lot, snapped to lotStep/minLot from instrumentConfig.js.
 * The SL +/- buttons navigate between *groups* of SL where that snapped lot
 * is constant (see groupStartAt/nextGroupStart) instead of walking SL cent
 * by cent, and the chips are generated by walking those same real groups
 * (generateGroupChips) instead of being static presets.
 */

/** Balance * Risk% → dollars at risk. Risk% is a plain number (0.7 = 0.7%,
 *  NOT a 0-1 fraction) matching how it's entered/displayed in the UI. */
export function riskDollarFromPercent(balance, riskPercent) {
  const b = Number(balance) || 0;
  const p = Number(riskPercent) || 0;
  return b * (p / 100);
}

/** Inverse of the above — used when the user edits Riesgo($) directly, so
 *  Riesgo(%) can be kept in sync against the same Balance. */
export function riskPercentFromDollar(balance, riskDollar) {
  const b = Number(balance) || 0;
  if (b <= 0) return 0;
  const d = Number(riskDollar) || 0;
  return (d / b) * 100;
}

/** RiesgoUSD / (SL * pointValue) — the core formula, Excel cell C2. Returns
 *  0 (not NaN/Infinity) for any invalid input so the UI never has to guard
 *  against displaying garbage while a field is mid-edit or empty. */
export function calculateLot(riskDollar, slPoints, pointValue) {
  const r = Number(riskDollar) || 0;
  const sl = Number(slPoints) || 0;
  const pv = Number(pointValue) || 0;
  if (sl <= 0 || pv <= 0) return 0;
  return r / (sl * pv);
}

// ─── Display formatting ──────────────────────────────────────────────────
// Kept here (not scattered across components) so every widget/card formats
// the same kind of number identically, and so it's one place to adjust if
// the precision requirements ever change.
export const fmtMoney = v => `$${(Number(v) || 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
export const fmtPercent = v => `${(Number(v) || 0).toFixed(2)}%`;
export const fmtLot = v => (Number(v) || 0).toFixed(2);
export const fmtPoints = v => (Number(v) || 0).toFixed(2);

// ─── Lot precision — snapping the ideal lot to the broker's real grid ──────
// calculateLot() above returns a continuous, un-tradeable number. Everything
// below turns that into the lot the user can actually place, using only
// `lotStep`/`minLot` from instrumentConfig.js — never a hardcoded precision.
function decimalsOf(step) {
  const s = String(step);
  const i = s.indexOf(".");
  return i === -1 ? 0 : s.length - i - 1;
}

function snapToStep(value, step) {
  const d = decimalsOf(step);
  const factor = 10 ** d;
  return Math.round(Math.round(value / step) * step * factor) / factor;
}

function floorLot(idealLot, lotStep, minLot) {
  const snapped = snapToStep(Math.floor((idealLot - minLot) / lotStep) * lotStep + minLot, lotStep);
  return Math.max(minLot, snapped);
}

function ceilLot(idealLot, lotStep, minLot) {
  const snapped = snapToStep(Math.ceil((idealLot - minLot) / lotStep) * lotStep + minLot, lotStep);
  return Math.max(minLot, snapped);
}

/** The lot the user would actually place for this SL: the ideal continuous
 *  lot, snapped to the broker's grid by comparing the real $ risk of the
 *  lot immediately below vs. immediately above against the risk target, and
 *  keeping whichever is closer. On an exact tie, keeps the lower one (never
 *  exceeds the target) — since real risk grows with lot size, "lower lot"
 *  and "does not exceed target" are the same thing here. */
export function optimalLot(riskDollar, slPoints, pointValue, lotStep, minLot) {
  const ideal = calculateLot(riskDollar, slPoints, pointValue); // formula untouched
  if (ideal <= 0) return minLot;
  const lower = floorLot(ideal, lotStep, minLot);
  const upper = ceilLot(ideal, lotStep, minLot);
  if (lower === upper) return lower;
  const diffLower = Math.abs(realRiskFromLot(lower, slPoints, pointValue) - riskDollar);
  const diffUpper = Math.abs(realRiskFromLot(upper, slPoints, pointValue) - riskDollar);
  if (diffLower === diffUpper) return lower;
  return diffLower < diffUpper ? lower : upper;
}

/** The real dollar risk of an actual (already-snapped) lot — not the flat
 *  theoretical target. This is what the RISK figure shows: the true
 *  consequence of the lot the user would really place at this SL. */
export function realRiskFromLot(lot, slPoints, pointValue) {
  return (Number(lot) || 0) * (Number(slPoints) || 0) * (Number(pointValue) || 0);
}

// ─── Group navigation (for the SL +/- buttons) ─────────────────────────────
// A "group" is a maximal run of consecutive SL values (at SL_STEP
// resolution) that all resolve to the same optimalLot — the window where
// that lot is the best achievable approximation of the risk target. The
// +/- buttons navigate between groups, not individual SL values.
//
// The whole design leans on one idea: groupStartAt(sl) always returns the
// same representative for every SL inside the same group, regardless of
// which direction you arrived from. That single property is what makes
// navigation deterministic and reversible (+ then - always returns to
// where you started) — and it's also what fixes the manual-entry/
// navigation handoff for free: a +/- press always re-derives "which group
// am I in" from whatever SL is currently showing, whether that SL came
// from typing or from a previous navigation step, so there's no separate
// "mode" to get stuck in.
const SL_STEP = 0.01;          // matches the SL field's own decimal resolution
const SL_SEARCH_LIMIT = 20000; // hard cap (±200 pts) so a flat/edge-case
                                // instrument can never hang the UI searching
                                // for a group boundary that isn't there

function round2(v) {
  return Math.round((Number(v) || 0) * 100) / 100;
}

/** Walk backward from `sl` while the optimal lot stays the same, and return
 *  the first (lowest) SL in that run — the group's representative. */
export function groupStartAt(sl, riskDollar, pointValue, lotStep, minLot) {
  let cursor = round2(sl);
  const lot = optimalLot(riskDollar, cursor, pointValue, lotStep, minLot);
  for (let i = 0; i < SL_SEARCH_LIMIT; i++) {
    const prev = round2(cursor - SL_STEP);
    if (prev <= 0) return cursor; // hit the floor — this is as far back as it goes
    if (optimalLot(riskDollar, prev, pointValue, lotStep, minLot) !== lot) return cursor;
    cursor = prev;
  }
  return cursor;
}

/** The representative of the next group in `direction` (+1 or -1) from
 *  whatever group currently contains `sl`. */
export function nextGroupStart(sl, direction, riskDollar, pointValue, lotStep, minLot) {
  const start = groupStartAt(sl, riskDollar, pointValue, lotStep, minLot);
  if (direction > 0) {
    // Walk forward from the current group's start until the lot changes —
    // that first differing SL is, by construction, the next group's start.
    const lot = optimalLot(riskDollar, start, pointValue, lotStep, minLot);
    let cursor = start;
    for (let i = 0; i < SL_SEARCH_LIMIT; i++) {
      cursor = round2(cursor + SL_STEP);
      if (optimalLot(riskDollar, cursor, pointValue, lotStep, minLot) !== lot) return cursor;
    }
    return cursor;
  }
  // One step below the current group's start lands in the *previous*
  // group's last SL — resolve that back to its own start.
  const prevGroupTail = round2(start - SL_STEP);
  if (prevGroupTail <= 0) return start; // already at the floor
  return groupStartAt(prevGroupTail, riskDollar, pointValue, lotStep, minLot);
}

// ─── Dynamic chips ──────────────────────────────────────────────────────────
// Chips are group representatives, not arbitrary SL presets — tapping one
// jumps straight to that group the same way a +/- press would. They exist
// to get the user into the right *neighborhood* fast, so they optimize for
// coverage of the instrument's whole usable SL range, not for proximity to
// each other — walking consecutive nearby groups (the earlier approach)
// clusters all 14 chips a few points apart wherever the default happens to
// sit, which is exactly wrong for an instrument where a reasonable SL can
// be 2x or 3x the default.
//
// The range covered is proportional to the instrument's own `defaultSL`
// (COVERAGE_MIN_FACTOR–COVERAGE_MAX_FACTOR of it) rather than a fixed point
// count, so it scales correctly across wildly different instruments (SP500
// stops in single digits, US30 stops in the hundreds) without a second
// piece of per-instrument config. These factors are a starting heuristic —
// worth sanity-checking against real SL ranges you actually use.
//
// The caller (the widget) is responsible for memoizing this against
// [instrumentId, riskDollar] so the chips stay put — and muscle memory
// stays intact — until balance, risk, or instrument actually change.
const COVERAGE_MIN_FACTOR = 0.3; // lower bound of the covered SL range, as a multiple of defaultSL
const COVERAGE_MAX_FACTOR = 3.5; // upper bound of the covered SL range, as a multiple of defaultSL
const CHIP_OVERSAMPLE = 6;       // sample this many candidate points per chip requested, then
                                  // de-dupe by group and pick an evenly-spread subset — sampling
                                  // more than needed is what keeps coverage even even though real
                                  // group widths vary a lot across the range

function pickEvenlySpread(arr, count) {
  if (arr.length <= count) return arr;
  const picked = [];
  const step = (arr.length - 1) / (count - 1);
  for (let i = 0; i < count; i++) picked.push(arr[Math.round(i * step)]);
  return [...new Set(picked)];
}

export function generateGroupChips(defaultSl, riskDollar, pointValue, lotStep, minLot, count = 14) {
  const rangeMin = Math.max(minLot, round2(defaultSl * COVERAGE_MIN_FACTOR));
  const rangeMax = round2(defaultSl * COVERAGE_MAX_FACTOR);
  const sampleCount = count * CHIP_OVERSAMPLE;
  const step = (rangeMax - rangeMin) / (sampleCount - 1);

  const seen = new Set();
  const groupReps = [];
  for (let i = 0; i < sampleCount; i++) {
    const sampleSl = round2(rangeMin + i * step);
    const rep = groupStartAt(sampleSl, riskDollar, pointValue, lotStep, minLot);
    if (!seen.has(rep)) {
      seen.add(rep);
      groupReps.push(rep);
    }
  }

  return pickEvenlySpread(groupReps, count);
}
